name: Feature request
description: Suggest an idea for this project
title: '[Feature] '
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking your time to fill out a feature request. Remember
        to fill out all fields including the title above.

        An issue that is not properly filled out will be closed.
  - type: dropdown
    id: reference
    attributes:
      label: What does your feature refer to?
      options:
        - InGame
        - Website
        - Other
    validations:
      required: true
  - type: dropdown
    id: kind
    attributes:
      label: What kind of feature do you suggest?
      options:
        - label: Creature
        - label: NPC
        - label: Worldboss
        - label: Dungeon
        - label: Raid
        - label: Item
        - label: Profession
        - label: Quest
        - label: Spell
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your feature request or suggestion in detail
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe a possible solution to your feature or suggestion in detail
      description: >
        A clear and concise description of any alternative solutions or features
        you've considered.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution.