name: Assign to Project

on:
  issues:
    types: [opened]

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Add issue to project
    steps:
      - name: Assign new issues to SanctumWoW project 1
        uses: actions/add-to-project@v0.2.0
        with:
          project-url: 'https://github.com/orgs/SanctumWoW/projects/1'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
